// Responsive image pipeline. Reads the real project photography in
// image-masters/, emits AVIF/WebP/JPEG variants to public/img/, and writes a
// typed manifest (src/data/imageManifest.ts) with intrinsic dimensions + a
// tiny blur-up placeholder so <OptimizedImage> renders zero-CLS with warm
// blur backgrounds (never grey).
import { readdirSync, mkdirSync, writeFileSync, statSync } from "node:fs";
import { join, parse } from "node:path";
import sharp from "sharp";

const SRC = "image-masters";
const OUT = "public/img";
const WIDTHS = [400, 800, 1200, 1920];
const FORMATS = ["avif", "webp", "jpeg"];
const EXT = { avif: "avif", webp: "webp", jpeg: "jpg" };

mkdirSync(OUT, { recursive: true });

const files = readdirSync(SRC).filter((f) => /\.(jpe?g|png)$/i.test(f));
const manifest = {};
let generated = 0;

for (const file of files) {
  const key = parse(file).name; // e.g. "demon-tweeks-hero"
  const input = join(SRC, file);
  const meta = await sharp(input).metadata();
  const intrinsicW = meta.width || 1600;
  const intrinsicH = meta.height || 1000;

  const widths = WIDTHS.filter((w) => w <= intrinsicW);
  if (!widths.includes(intrinsicW) && widths[widths.length - 1] < intrinsicW && intrinsicW < WIDTHS[0]) {
    widths.push(intrinsicW);
  }
  if (widths.length === 0) widths.push(intrinsicW);

  for (const w of widths) {
    for (const fmt of FORMATS) {
      const outFile = join(OUT, `${key}-${w}.${EXT[fmt]}`);
      let pipeline = sharp(input).resize({ width: w, withoutEnlargement: true });
      if (fmt === "avif") pipeline = pipeline.avif({ quality: 55 });
      else if (fmt === "webp") pipeline = pipeline.webp({ quality: 72 });
      else pipeline = pipeline.jpeg({ quality: 78, mozjpeg: true });
      await pipeline.toFile(outFile);
      generated++;
    }
  }

  // warm blur-up placeholder (~24px webp as base64)
  const blurBuf = await sharp(input).resize({ width: 24 }).webp({ quality: 45 }).toBuffer();
  const blur = `data:image/webp;base64,${blurBuf.toString("base64")}`;

  manifest[key] = {
    width: intrinsicW,
    height: intrinsicH,
    widths,
    blur,
  };
}

const header = `// AUTO-GENERATED by scripts/generate-images.mjs — do not edit by hand.
// Keyed by master filename in image-masters/. Consumed by <OptimizedImage>.
export type ImageEntry = { width: number; height: number; widths: number[]; blur: string };
export const imageManifest: Record<string, ImageEntry> = `;

writeFileSync("src/data/imageManifest.ts", header + JSON.stringify(manifest, null, 0) + ";\n");
console.log(`Generated ${generated} files for ${files.length} masters. Manifest: ${Object.keys(manifest).length} keys.`);
