// All seven case studies, in the display order used on /our-work (drives
// prev/next links). Copy is genuine live-site copy with only the corrections
// specified in the brief. Meta panel facts are only those stated in the copy.
const projects = [
  {
    slug: "demon-tweeks-wrexham",
    title: "Demon Tweeks, Wrexham",
    metaTitle: "Demon Tweeks — Office Fit-Out Case Study | Direct Interiors",
    metaDesc:
      "Our largest office fit-out so far: transforming a new-build warehouse in Wrexham into vibrant offices, meeting rooms, a gym and canteen for Demon Tweeks.",
    location: "Wrexham",
    sector: "Commercial",
    services: ["Fit-Out", "Drylining", "Glass Partitions"],
    hero: "demon-tweeks-hero.jpg",
    heroAlt: "Demon Tweeks office fit-out with glass partitioning",
    thumb: "demon-tweeks-thumb.jpg",
    thumbAlt: "Demon Tweeks office interior, Wrexham",
    side: "demon-tweaks-side-image.jpg",
    sideAlt: "Open-plan office area at Demon Tweeks, Wrexham",
    summary: "Transforming a newly built warehouse into a vibrant multipurpose office environment.",
    intro: [
      "Demon Tweeks were the end users of our largest office project so far. We carried out extensive interior works to transform this newly built warehouse into a vibrant office environment, suitable for office employees with comfort right at the heart of the design.",
      "The floorplan was cleverly divided to create a multipurpose space including open offices, meeting rooms, collaborative working areas, a gym, kitchen and canteen area.",
    ],
    installed: {
      title: "We installed:",
      items: [
        "Drylining & Insulation",
        "Metal stud & track partitioning",
        "Plasterboard Ceilings",
        "Bespoke built feature bulkhead to accommodate lighting design",
        "Tape & Jointing/Plastering",
        "Fire proofing",
        "Glass partitioning",
        "Sliding glass doors",
        "Glass Balustrade",
        "Doors & Frames",
        "Skirting & Architraves",
        "Flooring",
      ],
    },
    outro: [
      "Both the client and lead contractor found our work to be of exceptional quality, and finished to a standard which can be enjoyed for years to come.",
      "Please take a minute to view the gallery of pictures throughout the build.",
    ],
    gallery: [
      { src: "demon-tweeks-gallery01.jpg", alt: "Demon Tweeks fit-out — open-plan office with new partitioning" },
      { src: "demon-tweeks-gallery02.jpg", alt: "Demon Tweeks fit-out — meeting room with glass partitions" },
      { src: "demon-tweeks-gallery03.jpg", alt: "Demon Tweeks fit-out — feature bulkhead and lighting" },
      { src: "demon-tweeks-gallery04.jpg", alt: "Demon Tweeks fit-out — finished office interior" },
    ],
    relatedSolutions: ["interior-fit-outs-and-refurbishments", "partition-walls-drylining"],
  },
  {
    slug: "doc-fictoria-welsh-government",
    title: "Doc Fictoria, Welsh Government",
    metaTitle: "Doc Fictoria — Office Fit-Out Case Study | Direct Interiors",
    metaDesc:
      "Commercial office fit-out for the Welsh Government at Doc Fictoria — glazed screens, suspended ceilings and a timber feature wall turning a shell into a workspace.",
    location: "Doc Fictoria",
    sector: "Public",
    services: ["Fit-Out", "Glass Partitions", "Suspended Ceilings"],
    hero: "doc-fictoria-hero-4946c7c6.jpg",
    heroAlt: "Doc Fictoria office fit-out for the Welsh Government",
    thumb: "doc-fictoria-thumb.jpg",
    thumbAlt: "Doc Fictoria office interior for the Welsh Government",
    side: "doc-fictoria-side.jpg",
    sideAlt: "Glazed screens and timber feature wall at Doc Fictoria",
    summary: "Turning a lifeless shell into a functional, vibrant workspace for the Welsh Government.",
    intro: [
      "The Welsh Government were the beneficiaries of this delightful commercial office fit-out.",
      "We were contacted to undertake extensive interior works to transform this lifeless shell into a functional, vibrant workspace suitable for our prestigious client. This is one of our largest office projects so far and the results really speak for themselves.",
      "The brief was to create a practical office environment for our clients to feel comfortable whilst productivity was at the forefront of their day-to-day routines.",
    ],
    installed: {
      title: "We installed:",
      items: [
        "Metal stud & track partition walls",
        "Glass Partitioning (glazed screens)",
        "Suspended & Plasterboard ceilings",
        "Insulation",
        "Lighting & Power",
        "Timber feature wall",
        "Decoration",
        "Tape & Jointing/Plastering",
        "Doors & Frames",
        "Skirting & Architraves",
        "Kitchen",
      ],
    },
    outro: [
      "Through working with an experienced office fit-out company in Direct Interiors, the Welsh Government now has a practical, intelligently-configured workspace suitable for its day-to-day operations.",
      "Please take a minute to view the gallery throughout the build — you will not be disappointed.",
    ],
    gallery: [
      { src: "doc-fictoria-gallery01.jpg", alt: "Doc Fictoria fit-out — glazed partition screens" },
      { src: "doc-fictoria-gallery02.jpg", alt: "Doc Fictoria fit-out — open-plan workspace" },
      { src: "doc-fictoria-gallery03.jpg", alt: "Doc Fictoria fit-out — timber feature wall" },
      { src: "doc-fictoria-gallery04.jpg", alt: "Doc Fictoria fit-out — completed office interior" },
    ],
    relatedSolutions: ["interior-fit-outs-and-refurbishments", "suspended-ceilings"],
  },
  {
    slug: "padeswood-buckley-golf-club",
    title: "Padeswood & Buckley Golf Club",
    metaTitle: "Padeswood & Buckley GC — Washrooms Case Study | Direct Interiors",
    metaDesc:
      "A tired golf club washroom transformed in four weeks — hygienic cladding, anti-slip flooring and three extra showers without compromising the toilet facilities.",
    sector: "Leisure & Sport",
    duration: "4 weeks start to finish",
    services: ["Washrooms", "Hygienic Cladding"],
    hero: "padeswood-golf-club-hero-3d2efa71.jpg",
    heroAlt: "Refurbished washroom at Padeswood & Buckley Golf Club",
    thumb: "padeswood-buckley-golf-club-thumb.jpg",
    thumbAlt: "Padeswood & Buckley Golf Club washroom refurbishment",
    side: "padeswood-golf-club-side.jpg",
    sideAlt: "New shower facilities at Padeswood & Buckley Golf Club",
    summary: "A complete men’s washroom renovation delivering three extra showers in four weeks.",
    intro: [
      "We were approached by Padeswood & Buckley GC to renovate the Men’s WC area with a modernised, stylish look but keep the practicality of the WC for the members. The main concern was enhancing their showering facilities but not wanting to compromise too much of the space. We set up a meeting with the members to listen to their ideas which allowed us to gain an insight to what they were after.",
    ],
    installed: {
      title: "Works incorporated:",
      items: [
        "Rip out",
        "Boarding walls",
        "PVC Hygienic wall cladding",
        "Self-levelling floor",
        "Laying anti-slip vinyl floor",
        "Electrical & Plumbing",
        "Cubicles, Privacy Screens",
        "Toilets",
        "Showers",
        "Shower tray",
        "Sinks",
        "Accessories",
      ],
    },
    outro: [
      "We truly transformed a tired wash room into a sparkling new facility area for all the members. The design we created helped us create an additional 3 showers whilst not compromising the toilet facilities.",
      "Speaking to one of the members after the project was handed over, he said the following:",
    ],
    quote: "padeswood-member",
    afterQuote: ["Please have a look at some of this wonderful renovation via our gallery."],
    gallery: [
      { src: "padeswood-golf-club-gallery01.jpg", alt: "Padeswood & Buckley — new washroom cubicles" },
      { src: "padeswood-golf-club-gallery02.jpg", alt: "Padeswood & Buckley — hygienic wall cladding" },
      { src: "padeswood-golf-club-gallery03.jpg", alt: "Padeswood & Buckley — new shower facilities" },
      { src: "padeswood-golf-club-gallery04.jpg", alt: "Padeswood & Buckley — finished washroom" },
    ],
    relatedSolutions: ["washroom-refurbishments", "hygienic-wall-cladding"],
  },
  {
    slug: "butchers-dyserth",
    title: "Butchers, Dyserth",
    metaTitle: "Butchers, Dyserth — Renovation Case Study | Direct Interiors",
    metaDesc:
      "A full butcher’s shop renovation in Dyserth — clean care ceiling, hygienic cladding and anti-slip flooring, followed by a 5-out-of-5 food hygiene rating.",
    location: "Dyserth",
    sector: "Retail",
    services: ["Suspended Ceilings", "Hygienic Cladding"],
    hero: "butchers-hero.jpg",
    heroAlt: "Renovated butcher’s shop interior in Dyserth",
    thumb: "dyserth-butchers-thumb.jpg",
    thumbAlt: "Butcher’s shop renovation in Dyserth",
    side: "butchers-side.jpg",
    sideAlt: "Hygienic wall cladding and clean care ceiling in the butcher’s shop",
    summary: "A full shop renovation before a health inspection — rewarded with a 5-out-of-5 rating.",
    intro: [
      "One of our smaller projects undertaken, but no less important, with the same attention to detail. Billy contacted us asking whether we could install a suspended ceiling within his butchers before an upcoming health & hygiene inspection. When we arrived on site, he soon realised we could offer the full renovation he was looking for! All with trades employed to Direct Interiors.",
    ],
    installed: {
      title: "Our works included:",
      items: ["Clean Care Suspended Ceiling", "LED lighting", "Hygienic wall cladding", "Anti-slip vinyl floor"],
    },
    outro: [
      "Shortly after the project was finished the health & hygiene inspection was undertaken and the butchers was awarded a 5-out-of-5 food hygiene rating. Another successful project delivered within a limited time restraint.",
      "Please view our gallery of the project.",
    ],
    gallery: [
      { src: "butchers-gallery01.jpg", alt: "Butchers Dyserth — clean care suspended ceiling" },
      { src: "butchers-gallery02.jpg", alt: "Butchers Dyserth — hygienic wall cladding" },
      { src: "butchers-gallery03.jpg", alt: "Butchers Dyserth — anti-slip vinyl flooring" },
      { src: "butchers-gallery04.jpg", alt: "Butchers Dyserth — finished shop renovation" },
    ],
    relatedSolutions: ["suspended-ceilings", "hygienic-wall-cladding"],
  },
  {
    slug: "matthew-arnold-primary-school-liverpool",
    title: "Matthew Arnold Primary School, Liverpool",
    metaTitle: "Matthew Arnold School — Glass Partitions Case Study | Direct Interiors",
    metaDesc:
      "A freestanding DSi framed glass partition with double doors, engineered around a high ceiling to separate reception from the school beyond — without losing light.",
    location: "Liverpool",
    sector: "Education",
    services: ["Glass Partitions"],
    hero: "matthew-primary-hero.jpg",
    heroAlt: "Freestanding glass partition at Matthew Arnold Primary School",
    thumb: "matthew-arnold-primary-thumb.jpg",
    thumbAlt: "Glass partition installation at Matthew Arnold Primary School",
    side: "matthew-primary-side.jpg",
    sideAlt: "DSi framed glass partition with double doors at the school reception",
    summary: "A freestanding glass partition engineered to separate reception without losing light.",
    intro: [
      "MAPS, Liverpool benefitted from one of our new freestanding DSi framed glass partitioning systems complete with glass double doors. They connected with us to produce some plans they had put together for a separation of reception/entrance to the school kids.",
      "The problem they had with ideas was the height of the existing ceiling — without a beneficial fix to the ceiling they wouldn’t be able to build anything. This is where Direct Interiors stepped in: we showed them a past design and project we had completed before, which we braced from external walls. We took this idea forward and utilised it with the design of the glass partition. We calculated with our manufacturer & supplier the weight of the glass partitioning when free standing and figured out our bracing strategy. All paperwork and evidence to support the calculations were provided to the governing body of the school when pre-site meetings were held throughout before the commencement of work.",
      "Matthew Arnold Primary School now has a stylish separation between reception and the school beyond.",
      "After the handover, the receptionist of the school said:",
    ],
    quote: "matthew-arnold",
    afterQuote: ["Please view our photos of the project!"],
    gallery: [
      { src: "matthew-primary-gallery01.jpg", alt: "Matthew Arnold — freestanding glass partition frame" },
      { src: "matthew-primary-gallery02.jpg", alt: "Matthew Arnold — glass double doors at reception" },
      { src: "matthew-primary-gallery03.jpg", alt: "Matthew Arnold — bracing detail above the partition" },
      { src: "matthew-primary-gallery04.jpg", alt: "Matthew Arnold — completed reception separation" },
    ],
    relatedSolutions: ["glass-partitions"],
  },
  {
    slug: "bell-meadow-business-park-chester",
    title: "Bell Meadow Business Park, Chester",
    metaTitle: "Bell Meadow — Bespoke Office Case Study | Direct Interiors",
    metaDesc:
      "One of our most unique office designs — a black-sprayed exposed ceiling, open-plan layout and high-end finishes that saw the space let within a week of handover.",
    location: "Chester",
    sector: "Commercial",
    services: ["Fit-Out", "Bespoke Designs"],
    hero: "bell-meadow-hero-0a75fafa.jpg",
    heroAlt: "Bespoke office interior with black-sprayed ceiling at Bell Meadow Business Park",
    thumb: "bell-meadow-thumb.jpg",
    thumbAlt: "Bespoke office design at Bell Meadow Business Park, Chester",
    side: "bell-meadow-side.jpg",
    sideAlt: "Open-plan office with suspended LED lighting at Bell Meadow",
    summary: "A stand-out office design with a black-sprayed ceiling — let within a week of handover.",
    intro: [
      "One of our most unique designs for an office space yet. Incorporating the latest trends, we were asked to come up with ideas to make this office area ‘stand out’ from the usual dull, boring office environment.",
      "With the main focus being ‘standing out from the crowd’, we scrapped the usual ideas of a new suspended ceiling, lighting and partition walls and went for a complete spray of the existing ceiling in the colour black. We opted for an open-plan look with new carpets, kitchen, suspended LED lighting all to comply with regulations. We gave the place a ‘facelift’ with full decoration to external walls finished off with timber glossed trims to create that high-end finish.",
    ],
    outro: [
      "Bell Meadow Business Park management team received emails & calls from many different companies wanting to view or occupy the place as soon as it was on the rental market.",
      "Within a week of the handover, the space was taken and being utilised. Another fantastic environment to work from — and the end results speak for themselves.",
    ],
    gallery: [
      { src: "bell-meadow-gallery01.jpg", alt: "Bell Meadow — black-sprayed exposed ceiling" },
      { src: "bell-meadow-gallery02.jpg", alt: "Bell Meadow — open-plan office with suspended LED lighting" },
      { src: "bell-meadow-gallery03.jpg", alt: "Bell Meadow — kitchen area with high-end finishes" },
      { src: "bell-meadow-gallery04.jpg", alt: "Bell Meadow — completed office space" },
    ],
    relatedSolutions: ["interior-fit-outs-and-refurbishments", "bespoke-designs"],
  },
  {
    slug: "westrock-wrexham",
    title: "Westrock, Wrexham",
    metaTitle: "Westrock — Glass Partitioning Case Study | Direct Interiors",
    metaDesc:
      "DSi frameless glass partitioning with sliding and pivot doors, dividing open offices into two directors’ offices and a boardroom without losing natural light.",
    location: "Wrexham",
    sector: "Commercial",
    services: ["Glass Partitions", "Drylining"],
    hero: "westrock-wrexham-hero.jpg",
    heroAlt: "Frameless glass partitioning at Westrock, Wrexham",
    thumb: "westrock-thumb.jpg",
    thumbAlt: "DSi frameless glass partitions at Westrock, Wrexham",
    side: "westrock-wrexham-side-e557a1c3.jpg",
    sideAlt: "Boardroom created with DSi frameless glazing at Westrock",
    summary: "Stunning frameless glazing creating two directors’ offices and a boardroom.",
    intro: [
      "Westrock, Wrexham were the end users of this stunning glass partitioning. We were instructed to split the existing offices up to accommodate 2 directors’ offices and 1 boardroom/meeting room. Accommodating the high ceilings and the natural light provided, we offered our DSi frameless glass partitioning complete with 1 set of sliding glass doors and 2 single pivot glass doors.",
      "The directors wanted their own space, but didn’t want to feel isolated from the group. DSi frameless glass incorporates practicality, whilst providing privacy from external sound transference.",
    ],
    installed: {
      title: "We installed:",
      items: [
        "Metal stud & track partitioning",
        "DSi Frameless glass partitioning",
        "DSi Sliding glass doors",
        "Bespoke built bulkhead to accommodate DSi frameless glazing",
        "Tape & Joint finish",
        "Decoration",
        "Insulation",
      ],
    },
    outro: [
      "Both the client and lead contractor found our work to be of exceptional quality, and finished to a standard which can be enjoyed for years to come.",
      "Please take a minute to view the gallery of pictures throughout the build.",
    ],
    gallery: [
      { src: "westrock-wrexham-gallery01.jpg", alt: "Westrock — boardroom with DSi frameless glazing" },
      { src: "westrock-wrexham-gallery02.jpg", alt: "Westrock — sliding glass doors" },
      { src: "westrock-wrexham-gallery03.jpg", alt: "Westrock — directors’ office partitions" },
      { src: "westrock-wrexham-gallery04.jpg", alt: "Westrock — completed glass partitioning" },
    ],
    relatedSolutions: ["glass-partitions", "partition-walls-drylining"],
  },
];

// Wire prev/next so the pager never needs index arithmetic in templates.
projects.forEach((p, i) => {
  const prev = projects[(i - 1 + projects.length) % projects.length];
  const next = projects[(i + 1) % projects.length];
  p.prev = { slug: prev.slug, title: prev.title };
  p.next = { slug: next.slug, title: next.title };
});

module.exports = projects;
