// All seven solutions pages. Copy is the genuine live-site copy with only the
// corrections specified in the brief (grammar/typo fixes, no rewrites).
module.exports = [
  {
    slug: "interior-fit-outs-and-refurbishments",
    title: "Interior Fit-Outs & Refurbishments",
    strapline: "Replace – Renovate – Create",
    navLabel: "Interior Fit-Outs and Refurbishments",
    cardTitle: "Interior Fit-Outs",
    cardImage: "feature-interior-fit-outs.jpg",
    cardAlt: "Newly fitted-out modern office interior",
    cardBlurb: "Complete office fit-outs and refurbishments — replace, renovate, create.",
    metaTitle: "Office Fit-Outs in Chester & North Wales | Direct Interiors",
    metaDesc:
      "Commercial fit-outs and office refurbishments across Chester, Deeside and the North West. One project manager, all trades in-house, on time and on budget. Get a free quote.",
    hero: "interior-fit-out-hero-new.jpg",
    heroAlt: "Bright refurbished open-plan office fit-out",
    intro: [
      "Direct Interiors have the powers to truly transform a workspace, an opportunity to embrace modern trends and introduce more diverse working facilities to enhance your production and workplace.",
      "So, whether you want a complete new office uplift, additional offices or a new layout to create more space to facilitate options like agile working, we recommend speaking to one of our specialists. We start by getting to know you and your business first. We listen to your vision before applying our skills to create a bespoke, innovative design that accommodates your budget and aspirations.",
    ],
    body: [
      "We offer insights into current interior design trends and an extensive knowledge of product development to truly transform workspaces. We have a collection of latest projects we can share to support and enhance our ideas.",
      "Here at Direct Interiors, a Project Manager will be your single point of contact to handle every detail and ensure that your project is delivered on time and within budget.",
      "We will be with you every step of the way and we look forward to making your vision become a reality.",
    ],
    sideImages: [
      { src: "interior-fit-out-side01.jpg", alt: "Office fit-out in progress with new partition walls" },
      { src: "interior-fit-out-side02.jpg", alt: "Completed office refurbishment with modern finishes" },
    ],
    testimonial: "kinnerton-long",
    related: ["demon-tweeks-wrexham", "doc-fictoria-welsh-government", "bell-meadow-business-park-chester"],
  },
  {
    slug: "suspended-ceilings",
    title: "Suspended Ceilings",
    navLabel: "Suspended Ceilings",
    cardTitle: "Suspended Ceilings",
    cardImage: "feature-suspended-ceilings.jpg",
    cardAlt: "Suspended ceiling with recessed LED panels",
    cardBlurb: "Innovative ceiling designs fit for purpose, fitted with minimum disruption.",
    metaTitle: "Suspended Ceilings in North Wales & Chester | Direct Interiors",
    metaDesc:
      "Suspended ceiling installation across North Wales, Chester and the North West — acoustic, hygienic and MF plasterboard ceilings fitted with minimum disruption. Free quotes.",
    hero: "suspended-ceilings-hero-new.jpg",
    heroAlt: "New suspended ceiling installation with integrated lighting",
    intro: [
      "Direct Interiors specialise within the installation of suspended ceilings. We carry out professional fitting with minimum disruption to you or your business operation.",
    ],
    checklist: {
      title: "Our services include:",
      items: [
        "Acoustic Ceilings",
        "Suspended Ceilings",
        "Hygienic/Clean care ceilings",
        "MF Plasterboard Ceilings",
        "Bulkheads (bespoke to you)",
        "Ceiling Troughs to accommodate lighting",
        "Arched Barrel Ceilings",
      ],
    },
    body: [
      "At Direct Interiors, we can provide you with expert help, advice and guidance on your ceiling requirements. We can provide data sheets of products and a gallery of past projects to support the information presented.",
    ],
    sideImages: [
      { src: "suspended-ceilings-side01.jpg", alt: "Suspended ceiling grid being installed" },
      { src: "suspended-ceilings-side02.jpg", alt: "Finished suspended ceiling with LED panels" },
    ],
    testimonial: "karai",
    related: ["butchers-dyserth", "demon-tweeks-wrexham"],
  },
  {
    slug: "partition-walls-drylining",
    title: "Partitions & Drylining",
    navLabel: "Partition Walls & Drylining",
    cardTitle: "Partition Walls & Drylining",
    cardImage: "feature-partition-walls.jpg",
    cardAlt: "New partition walls dividing an office space",
    cardBlurb: "Create rooms and transform areas and workspaces with flexible partitioning.",
    metaTitle: "Partition Walls & Drylining, Chester | Direct Interiors",
    metaDesc:
      "Partition walls and drylining for offices and commercial premises in Chester, Deeside and the North West. British Gypsum, Siniat and Knauf systems. Get a free quote.",
    hero: "partitions-drylining-hero-new.jpg",
    heroAlt: "Metal stud partition walls under construction",
    intro: [
      "If you have an expanding business, why not consider partitioning systems for the flexibility to adapt your space to your needs quickly?",
      "Partitioning systems are the perfect solution to a demanding environment where change is constant.",
      "Re-designing your existing space can also present a cost-effective alternative to relocation. Partitions are a fast, easy and cost-effective way of making a division wall in any room.",
    ],
    checklist: {
      title: "Partitions can be used for a number of specifications including:",
      items: ["Fire integrity", "Sound absorption", "Impact resistance", "Thermal conductivity"],
    },
    body: [
      "Direct Interiors installs a comprehensive range of internal drylining systems. Designs allow for differing structural requirements, fire ratings, sound insulation, thermal insulation and vapour control, and are installed in accordance with the strict requirements of leading manufacturers.",
    ],
    systems: ["British Gypsum", "Siniat", "Knauf"],
    sideImages: [{ src: "partitions-drylining-side01.jpg", alt: "Drylining boards fitted to a partition wall" }],
    testimonial: "kinnerton-short",
    related: ["westrock-wrexham", "doc-fictoria-welsh-government"],
  },
  {
    slug: "glass-partitions",
    title: "Glass Partitions",
    navLabel: "Glass Partitions",
    cardTitle: "Glass Partitions",
    cardImage: "feature-glass-partition.jpg",
    cardAlt: "Frameless glass office partitions",
    cardBlurb: "Bespoke glazing that keeps offices bright, modern and stylish.",
    metaTitle: "Glass Partitions in Chester & North Wales | Direct Interiors",
    metaDesc:
      "DSi framed and frameless glass partitions for offices in Chester, North Wales and the North West. Bright, modern meeting rooms without losing natural light. Free quotes.",
    hero: "glass-partitions-hero-69cd9864.jpg",
    heroAlt: "Glass partition wall with a glazed door in a modern office",
    intro: [
      "Direct Interiors are committed to create a bright, airy and modern atmosphere in your office with the help of our DSi frame and frameless partitioning systems.",
    ],
    checklist: {
      title: "Why choose a glass partition system?",
      items: [
        "Fast installation – our glass partition systems are super quick to fit, meaning there will be minimum disruption to your business.",
        "Privacy – glass partitions are great at absorbing sound, helping to create a more private space for HR, credit control and admin teams without the feeling of being cut off from other employees.",
        "Bespoke – add corporate branding, colours and logos to your glazing to help it fit in with your workplace.",
        "Uplift in light allowance – unlike solid walls, glass partitions allow light to flow between spaces, helping to keep your office bright and airy.",
        "Appearance – DSi framed and frameless partitioning systems are unique and classy. A bespoke-built, stylish partition in an office space can make the room feel bigger with more light enhancement, but also gives privacy when required.",
      ],
    },
    note: {
      title: "Additional note to consider:",
      text: "The DSi framed system can come in any RAL colour and our double-glazed system can also include integral blinds as an added feature.",
    },
    body: [
      "Whether you’re looking to create meeting rooms or are simply looking for a way to divide an existing space without the limitations of a solid wall — from single glazed partitions to double glazed, fire-rated, framed and frameless — we’ll be happy to discuss which solutions are best suited to you.",
    ],
    sideImages: [
      { src: "glass-partitions-side01.jpg", alt: "Framed glass partitions forming a meeting room" },
      { src: "glass-partitions-side02.jpg", alt: "Frameless glass partition with sliding door" },
    ],
    testimonial: "matthew-arnold",
    related: ["westrock-wrexham", "matthew-arnold-primary-school-liverpool", "bell-meadow-business-park-chester"],
  },
  {
    slug: "hygienic-wall-cladding",
    title: "Hygienic Wall Cladding",
    navLabel: "Hygienic Wall Cladding",
    cardTitle: "Hygienic Wall Cladding",
    cardImage: "feature-hygienic-wall-cladding01.jpg",
    cardAlt: "White hygienic wall cladding in a commercial kitchen",
    cardBlurb: "Washable, wipeable, FDA-approved cladding that meets building regulations.",
    metaTitle: "Hygienic Wall Cladding, North West | Direct Interiors",
    metaDesc:
      "Hygienic uPVC wall cladding supplied and installed across the North West and North Wales — kitchens, food prep, clinical and washroom areas. FDA approved. Free quotes.",
    hero: "hygienic-wall-cladding-hero.jpg",
    heroAlt: "Hygienic wall cladding installed in a food preparation area",
    intro: [
      "Chosen from years of installation experience, at Direct Interiors we supply and install only the highest quality hygienic uPVC wall cladding sheets and accessories.",
    ],
    checklist: {
      title: "Hygienic PVC wall cladding advantages:",
      items: [
        "Cost effective",
        "FDA approved",
        "Meets building regulations and health & safety standards",
        "Washable & wipeable",
        "Good impact protection",
        "High chemical resistance",
        "Long lasting — life expectancy of 25 years",
        "Sheet sizes are all 1220mm wide by 2440mm, 2750mm or 3050mm",
        "Available in a range of colours (standard colour is white)",
      ],
    },
    checklist2: {
      title: "Suitable locations:",
      items: ["Kitchens", "Food preparation areas", "Washrooms", "Toilets", "Clinical areas", "Hygienic areas", "Fridges"],
    },
    sideImages: [
      { src: "hygienic-wall-cladding-side01.jpg", alt: "Hygienic cladding sheets fitted to kitchen walls" },
      { src: "hygienic-wall-cladding-side02.jpg", alt: "Wipeable hygienic wall cladding in a clinical area" },
    ],
    testimonial: "golden-fish",
    related: ["butchers-dyserth", "padeswood-buckley-golf-club"],
  },
  {
    slug: "washroom-refurbishments",
    title: "Washroom Refurbishments",
    navLabel: "Washroom Refurbishments",
    cardTitle: "Washroom Refurbishments",
    cardImage: "feature-washroom-refurb.jpg",
    cardAlt: "Refurbished commercial washroom with new cubicles",
    cardBlurb: "Solid grade laminates and solid surfaces — functional, DDA-compliant washrooms.",
    metaTitle: "Washroom Refurbishment Contractors | Direct Interiors",
    metaDesc:
      "Commercial washroom refurbishments across Chester, Deeside and the North West. DDA-compliant design, solid grade laminates, full installation under one roof. Free quotes.",
    hero: "washroom-refurb-hero.jpg",
    heroAlt: "Modern refurbished washroom with solid grade laminate cubicles",
    intro: [
      "Are you looking to bring existing facilities up to regulations to accommodate changes within your business, or simply give your toilets a “face-lift” and bring them up to date?",
      "Our service is tailored to suit your requirements, taste and budget.",
      "We can produce an array of innovative designs of solid grade laminates and solid surfaces to create the perfect functional environment — whilst complying with all DDA regulations.",
    ],
    body: [
      "The wide array of products we use enables us to undertake and install the highest quality of washrooms, in any commercial setting. You can be sure that with us, you will get the correct balance of form and functionality in order to deliver premium finishes.",
      "From the initial site survey, design and interior layout, removal of existing sanitaryware and cubicles, to the installation of your new facilities — we can take care of it all, under one roof.",
      "We are a true “one stop shop”.",
    ],
    sideImages: [{ src: "washroom-refurb-side01.jpg", alt: "New washroom cubicles and sanitaryware installation" }],
    testimonial: "aura-washrooms",
    related: ["padeswood-buckley-golf-club", "butchers-dyserth"],
  },
  {
    slug: "bespoke-designs",
    title: "Bespoke Designs",
    navLabel: "Bespoke Designs",
    cardTitle: "Bespoke Designs",
    cardImage: "bespoke-designs-side01.jpg",
    cardAlt: "Bespoke timber feature wall in a commercial interior",
    cardBlurb: "Visionary designs brought to life — media walls, timber ceilings and more.",
    metaTitle: "Bespoke Interior Designs, Chester | Direct Interiors",
    metaDesc:
      "Bespoke commercial interiors across Chester and the North West — media walls, timber ceilings, mood rooms and curved walls, designed and built around your vision.",
    hero: "bespoke-designs-hero-new.jpg",
    heroAlt: "Bespoke designed interior with feature ceiling",
    intro: [
      "Direct Interiors’ bespoke design service speaks for itself; our gallery is full of in-trend and fashionable ideas from previous projects and gives you a great insight of what we can create for you.",
    ],
    checklist: {
      title: "Installations of:",
      items: [
        "Media walls bespoke built to suit your equipment",
        "Timber ceilings",
        "Timber wall panelling",
        "Mood rooms/showrooms",
        "Curved walls & ceilings",
        "Sliding doors",
      ],
    },
    body: [
      "Direct Interiors have the skills to integrate any of these designs into your environment. We innovate each design specifically for your requirements, so do not worry about sizing or spacing issues as we can create something individual to you.",
      "You tell us your vision and we take care of the rest.",
    ],
    sideImages: [{ src: "bespoke-designs-side01.jpg", alt: "Bespoke media wall and feature lighting" }],
    testimonial: "padeswood-member",
    related: ["bell-meadow-business-park-chester", "demon-tweeks-wrexham"],
  },
];
